require 'rubygems'
require 'railsless-deploy'

set :application, "nodejs_app_test"

set :scm, :none
set :deploy_via, :copy
set :copy_compression, :bz2
set :repository, File.dirname(__FILE__)
set :deploy_to, "/home/nodejs/#{application}"
set :user, "nodejs"

server ENV["TARGET"], :app

# do not copy these options
ssh_options[:keys] = [File.join(File.dirname(__FILE__), "..", "ssh", "id_rsa")]
ssh_options[:paranoid] = false

envs = ""
envs += "http_proxy=#{ENV["PROXY"]} " if ENV["PROXY"]
envs += "http_proxy=http://#{ENV["PROXY_IP"]}:3128 " if ENV["PROXY_IP"]
# end

namespace :deploy do

  task :warp, :roles => :app do
    envs += "NO_WARP=#{ENV['NO_WARP']} " if ENV["NO_WARP"]
    run "cd #{release_path} && #{envs} $HOME/.warp/client/node/install.sh"
  end

  task :restart, :roles => :app do
    run "/etc/init.d/#{application} restart"
  end

end

after 'deploy:finalize_update', 'deploy:warp'

after 'deploy', 'deploy:restart'